/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Biryani Drink combo.glb -T 
Files: Biryani Drink combo.glb [18.37MB] > C:\Users\ADMIN\Downloads\Biryani Drink combo-transformed.glb [896.74KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Biryani_Drink_combo(props) {
  const { nodes, materials } = useGLTF('/models/gameAssets/Biryani Drink combo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 1.087, Math.PI / 2]} scale={0.002}>
        <mesh geometry={nodes.Mesh050.geometry} material={materials['curve wall.001']} />
        <mesh geometry={nodes.Mesh050_1.geometry} material={materials['soda.001']} />
        <mesh geometry={nodes.Mesh050_2.geometry} material={materials['Assets_COMBINED:aiStandardSurface3.001']} />
        <mesh geometry={nodes.Mesh050_3.geometry} material={materials['biryani.001']} />
        <mesh geometry={nodes.Mesh050_4.geometry} material={materials['matki.001']} />
        <mesh geometry={nodes.Mesh050_5.geometry} material={materials['Material.009']} />
      </group>
      <mesh geometry={nodes.model_0003.geometry} material={materials['Material.011']} position={[0.027, 0.01, 0.005]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-0.001, 0.001, 0.001]} />
    </group>
  )
}

useGLTF.preload('/models/gameAssets/Biryani Drink combo-transformed.glb')
