/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Bottle.glb -T 
Files: Bottle.glb [731.45KB] > C:\Users\ADMIN\Downloads\Bottle-transformed.glb [32.92KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Bottle(props) {
  const { nodes, materials } = useGLTF('/models/gameAssets/BottleNew.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh037.geometry} material={materials['metal cap']} />
      <mesh geometry={nodes.Mesh037_1.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.Mesh037_2.geometry} material={materials['GLASS.001']} />
    </group>
  )
}

useGLTF.preload('/models/gameAssets/BottleNew.glb')
