// import React from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'
// import { useEffect } from 'react'
// import * as THREE from 'three'
// import { RigidBody } from '@react-three/rapier'

// export function Motu(props) {
//     const group = React.useRef()
//     const { nodes, materials, animations, scene } = useGLTF('/models/Enemies/models/Enemies/motu-transformed.glb')
//     const { actions } = useAnimations(animations, group)

//     // // Modify material properties after loading
//     // useEffect(() => {
//     //     // Example: Change color of the material
//     //     if (materials) {
//     //         // Assuming 'carMaterial' is the material's name in the GLTF model
//     //         const carMaterial = materials['PaletteMaterial001'];
//     //         if (carMaterial) {
//     //             carMaterial.color.set('silver');  // Set to red
//     //             carMaterial.roughness = 0.4;      // Adjust roughness
//     //             carMaterial.metalness = 0;      // Adjust metalness
//     //             // carMaterial.emissive.set(0x00ff00); // Add emissive green glow
//     //         }
//     //     }
//     // }, [materials]);


//     useEffect(() => {

//         if (actions && actions["Walking"]) {
//             const action = actions["Walking"];
//             action.play();
//             action.setLoop(THREE.LoopRepeat, Infinity); // Set the animation to loop if needed
//         }
//     }, [actions]); // Run this effect once when actions are available

//     return (
//         <>
//         </>

//     )
// }

// useGLTF.preload('/models/Enemies/models/Enemies/motu-transformed.glb')





/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 motu.glb -T 
Files: motu.glb [49.31MB] > /Users/dhruvyadav/Desktop/models/Enemies/motu-transformed.glb [678.32KB] (99%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect } from 'react'
import * as THREE from 'three'


export function Motu(props) {
    const group = React.useRef()
    const { scene, animations } = useGLTF('/models/Enemies/motu-transformed.glb')
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
    const { nodes, materials } = useGraph(clone)
    const { actions } = useAnimations(animations, group)


    useEffect(() => {

        if (actions && actions["Walking"]) {
            const action = actions["Walking"];
            action.play();
            action.setLoop(THREE.LoopRepeat, Infinity); // Set the animation to loop if needed
        }
    }, [actions]); // Run this effect once when actions are available

    return (
        <group ref={group} {...props} dispose={null} scale={0.05} rotation={[0, 3 * Math.PI / 4, 0]} position={[0, 4, 0]}>
        {/* <group ref={group} {...props} dispose={null} scale={0.04} rotation={[0, 3 * Math.PI / 4, 0]} position={[0, 2.5, 0]}> */}
            <group name="AuxScene">
                <group position={[0, -92.412, -7.905]}>
                    <primitive object={nodes.mixamorigHips} />
                </group>
                <skinnedMesh name="Ch43" geometry={nodes.Ch43.geometry} material={materials.Ch43_Body} skeleton={nodes.Ch43.skeleton} position={[0, -92.412, -7.905]} />
            </group>
        </group>
    )
}

useGLTF.preload('/models/Enemies/motu-transformed.glb')














