/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Level 1 Environment 3.0.glb -T 
Files: Level 1 Environment 3.0.glb [23.6MB] > C:\Users\ADMIN\Downloads\Level 1 Environment 3.0-transformed.glb [1.3MB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Level1Environment(props) {
  const { nodes, materials } = useGLTF('models/Scene/Level 1 Environment 3.0-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-44.115, -0.03, 53.241]} scale={[0.008, 0.008, 0.011]}>
        <mesh geometry={nodes.Mesh043.geometry} material={materials['Material #80']} />
        <mesh geometry={nodes.Mesh043_1.geometry} material={materials['Material #78']} />
        <mesh geometry={nodes.Mesh043_2.geometry} material={materials['Material #81']} />
      </group>
      <mesh geometry={nodes.Blue_Buildings001.geometry} material={materials['Material #77']} position={[39.416, 11.091, 4.418]} rotation={[0, 1.571, 0]} scale={0.013} />
      <mesh geometry={nodes.Road.geometry} material={materials['Material.001']} position={[3.385, 0, 2.152]} rotation={[Math.PI / 2, 0, 0]} scale={112.923} />
      <mesh geometry={nodes.Side_Blockers.geometry} material={materials.lambert1} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Ground.geometry} material={materials.lambert2} position={[3.385, -0.478, 2.152]} rotation={[Math.PI / 2, 0, 0]} scale={112.923} />
      <mesh geometry={nodes.Green_Buildings.geometry} material={materials['Material #79']} position={[-28.403, 11.977, -43.797]} rotation={[0, -Math.PI / 2, 0]} scale={[0.012, 0.016, 0.009]} />
      <group position={[-1.951, 7.691, -23.456]} rotation={[Math.PI, -1.134, Math.PI]} scale={[0.021, 0.016, 0.021]}>
        <mesh geometry={nodes.Mesh657.geometry} material={materials['Material #68']} />
        <mesh geometry={nodes.Mesh657_1.geometry} material={materials['Material #69']} />
        <mesh geometry={nodes.Mesh657_2.geometry} material={materials['Material #71']} />
        <mesh geometry={nodes.Mesh657_3.geometry} material={materials['Material #70']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Scene/Level 1 Environment 3.0-transformed.glb')
